CREATE DATABASE IF NOT EXISTS sistema_login;

USE sistema_login;

CREATE TABLE IF NOT EXISTS usuario (

    id INT AUTO_INCREMENT PRIMARY KEY,

    nome VARCHAR(100) NOT NULL,

    email VARCHAR(150) NOT NULL UNIQUE,

    senha VARCHAR(255) NOT NULL,

    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);